//! Authentication module for Grove mobile access
//!
//! Supports two modes:
//! - **No auth** (`grove web`): all requests pass through
//! - **HMAC-SHA256** (`grove mobile`): every request must carry a valid signature;
//!   the secret key never travels over the wire

use axum::{
    body::Body,
    extract::{Json, Request},
    http::StatusCode,
    middleware::Next,
    response::{IntoResponse, Response},
};
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

type HmacSha256 = Hmac<Sha256>;

/// Label exposed to the frontend via `/auth/info`.
#[derive(Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AuthMode {
    None,
    Hmac,
}

/// Server authentication state.
pub struct ServerAuth {
    pub mode: AuthMode,
    /// `None` ⇒ no auth required.  `Some(sk)` ⇒ HMAC mode.
    pub secret_key: Option<String>,
    /// True when `secret_key` was generated by `generate_secret_key()` (i.e.
    /// the user accepted the auto-generate option at the interactive prompt).
    /// Used by the startup banner to warn that the key is ephemeral and
    /// won't survive restarts.
    pub key_is_generated: bool,
    /// True when the operator has declared this instance is reached from a
    /// different machine than the one Grove runs on — e.g. `grove web`
    /// published through a reverse proxy or tunnel (Cloudflare Access,
    /// Tailscale Funnel, ngrok…) with no HMAC auth of its own. `required`
    /// alone can't capture this: a no-auth `grove web` always reports
    /// `required: false` regardless of how it's actually reached. The
    /// frontend uses `remote || required` to decide whether a server-side
    /// native OS dialog (folder picker, "reveal in file manager", launching
    /// the default browser) would even be visible to the person making the
    /// request. Set via `grove web --remote`.
    pub remote: bool,
    /// A4 — authorization in code. Allowlist of sender identities (the
    /// `x-grove-sender` header) permitted to drive the *sensitive* routes
    /// that inject attacker-controllable text into a skip-permissions agent
    /// (`/tray/send-prompt`, `…/tasks/dispatch`). **Empty ⇒ enforcement off**
    /// (back-compat); non-empty ⇒ fail closed (a missing or unlisted sender is
    /// refused with 403). Populated from `GROVE_MOBILE_SENDER_ALLOWLIST`
    /// (comma-separated) at HMAC-server startup. A shared symmetric HMAC key
    /// can't cryptographically bind identity, so this is defense-in-depth /
    /// an audit tag / a per-sender kill-switch, not an auth boundary on its own.
    pub sender_allowlist: Vec<String>,
    /// A3 — audit sink for sensitive-route decisions, one JSON object per line.
    /// `None` ⇒ no audit. Populated from `GROVE_MOBILE_AUDIT_LOG`.
    pub audit_path: Option<std::path::PathBuf>,
    /// Nonce replay-prevention map: nonce → timestamp (epoch secs).
    used_nonces: Mutex<HashMap<String, i64>>,
}

impl ServerAuth {
    /// No authentication (localhost / `grove web`). `remote` should be true
    /// when the operator has declared this instance is published for
    /// access from a different machine (see [`ServerAuth::remote`]).
    pub fn no_auth(remote: bool) -> Self {
        Self {
            mode: AuthMode::None,
            secret_key: None,
            key_is_generated: false,
            remote,
            // No auth ⇒ loopback / trusted; the sensitive-route gates below
            // only engage in HMAC mode, so leave these inert.
            sender_allowlist: Vec::new(),
            audit_path: None,
            used_nonces: Mutex::new(HashMap::new()),
        }
    }

    /// HMAC-SHA256 authentication (`grove mobile`). `is_generated` should be
    /// true when the key came from `generate_secret_key()`, false when the
    /// user typed it at the interactive prompt. Always network-accessed by
    /// design, so `remote` is implicitly true — callers don't need to pass
    /// it (the frontend's `required` check already covers HMAC mode, but
    /// setting it here keeps `ServerAuth::remote` meaningful on its own).
    pub fn hmac(secret_key: String, is_generated: bool) -> Self {
        let sender_allowlist = std::env::var("GROVE_MOBILE_SENDER_ALLOWLIST")
            .ok()
            .map(|s| {
                s.split(',')
                    .map(|x| x.trim().to_string())
                    .filter(|x| !x.is_empty())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();
        let audit_path = std::env::var("GROVE_MOBILE_AUDIT_LOG")
            .ok()
            .filter(|s| !s.is_empty())
            .map(std::path::PathBuf::from);
        Self {
            mode: AuthMode::Hmac,
            secret_key: Some(secret_key),
            key_is_generated: is_generated,
            remote: true,
            sender_allowlist,
            audit_path,
            used_nonces: Mutex::new(HashMap::new()),
        }
    }

    /// A4 — is `sender` (the `x-grove-sender` header) allowed to drive a
    /// sensitive route? Enforcement is off (returns true) when the allowlist is
    /// empty; otherwise fail closed: a missing sender is refused.
    pub fn sender_allowed(&self, sender: Option<&str>) -> bool {
        if self.sender_allowlist.is_empty() {
            return true;
        }
        match sender {
            Some(s) => self.sender_allowlist.iter().any(|a| a == s),
            None => false,
        }
    }

    /// A3 — append one JSON line to the audit sink (best-effort; never blocks
    /// the request path on an I/O error). No-op when no sink is configured.
    pub fn audit(&self, method: &str, path: &str, sender: Option<&str>, outcome: &str) {
        let Some(p) = &self.audit_path else {
            return;
        };
        let line = serde_json::json!({
            "ts": chrono::Utc::now().to_rfc3339(),
            "method": method,
            "path": path,
            "sender": sender.unwrap_or(""),
            "outcome": outcome,
        });
        if let Ok(mut f) = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(p)
        {
            use std::io::Write;
            let _ = writeln!(f, "{}", line);
        }
    }

    /// Verify an HMAC-SHA256 signature.
    ///
    /// The message is `"{timestamp}|{nonce}|{METHOD}|{canonical_path}"`, where
    /// `canonical_path` is `path` plus a sorted, `&`-joined query string (see
    /// [`canonical_path`]). Caller is responsible for canonicalizing before
    /// passing the value in.
    ///
    /// A2 — body integrity: when `body_sha256` is `Some(digest)` the signed
    /// message is extended to `"{ts}|{nonce}|{METHOD}|{path}|{digest}"`, binding
    /// the request body into the signature so a LAN MITM can't rewrite it. The
    /// caller passes the digest **it recomputed from the received bytes** (not a
    /// client-supplied header), so a tampered body fails the check. `None`
    /// preserves the legacy body-less message for GET / WS-upgrade requests.
    pub fn verify_signature(
        &self,
        timestamp: &str,
        nonce: &str,
        method: &str,
        path: &str,
        signature: &str,
        body_sha256: Option<&str>,
    ) -> bool {
        let sk = match &self.secret_key {
            Some(sk) => sk,
            None => return true, // no auth mode
        };

        // 1. Timestamp window check (±60 s)
        let ts: i64 = match timestamp.parse() {
            Ok(v) => v,
            Err(_) => return false,
        };
        let now = chrono::Utc::now().timestamp();
        if (now - ts).abs() > 60 {
            return false;
        }

        // 2. Compute expected HMAC and verify in constant time — BEFORE touching
        //    the nonce map, so a request with an invalid signature can't consume
        //    (and thereby poison or pre-empt) a nonce it never legitimately held.
        let message = match body_sha256 {
            Some(digest) => format!("{}|{}|{}|{}|{}", timestamp, nonce, method, path, digest),
            None => format!("{}|{}|{}|{}", timestamp, nonce, method, path),
        };
        let mut mac =
            HmacSha256::new_from_slice(sk.as_bytes()).expect("HMAC accepts any key length");
        mac.update(message.as_bytes());
        // Decode the client-supplied hex signature and compare via the MAC's
        // constant-time `verify_slice` (avoids a timing side-channel on the tag).
        // A malformed hex signature simply fails to decode and is rejected.
        let provided = match hex::decode(signature) {
            Ok(b) => b,
            Err(_) => return false,
        };
        if mac.verify_slice(&provided).is_err() {
            return false;
        }

        // 3. Signature is valid → enforce single-use of the nonce. Check and
        //    insert atomically under the lock so concurrent replays of the same
        //    valid request can't both slip through.
        {
            let mut nonces = self.used_nonces.lock().expect("nonce lock poisoned");
            if nonces.contains_key(nonce) {
                return false; // replay
            }
            nonces.insert(nonce.to_string(), ts);
            // Purge stale nonces (> 120 s old)
            nonces.retain(|_, &mut t| (now - t).abs() <= 120);
        }

        true
    }
}

/// Generate a cryptographically random 64-character hex secret key.
pub fn generate_secret_key() -> String {
    let mut bytes = [0u8; 32];
    getrandom::getrandom(&mut bytes).expect("Failed to generate random bytes");
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

// ─── Middleware ──────────────────────────────────────────────────────────────

/// Extract a single value from a query string: `key=value&…`
fn query_param<'a>(query: &'a str, key: &str) -> Option<&'a str> {
    for part in query.split('&') {
        if let Some(value) = part
            .strip_prefix(key)
            .and_then(|rest| rest.strip_prefix('='))
        {
            if !value.is_empty() {
                return Some(value);
            }
        }
    }
    None
}

/// Build the canonical path-and-query used as the `path` segment of the HMAC
/// message. Query parameters are sorted by `(key, value)` ascending and
/// joined with `&`. `exclude_keys` are dropped (used to strip `ts/nonce/sig`
/// when validating WebSocket upgrade requests that carry the signature in
/// the query string itself). Returns just `path` when there is no remaining
/// query.
///
/// IMPORTANT: this canonicalization is **byte-level**, not semantic-URL.
/// We do not percent-decode keys or values, do not collapse `+` to space,
/// do not normalize empty values, and do not unify multiple slashes. The
/// client signing the request MUST emit the exact same bytes — produce its
/// query by sorting `(key, value)` pairs ascending and joining with `&`,
/// matching whatever percent-encoding the server will see in the URL.
/// Mismatches at this layer produce `401 Invalid signature` even though
/// the URLs are semantically equivalent.
pub fn canonical_path(path: &str, query: Option<&str>, exclude_keys: &[&str]) -> String {
    let q = match query {
        Some(q) if !q.is_empty() => q,
        _ => return path.to_string(),
    };
    let mut pairs: Vec<(&str, &str)> = Vec::new();
    for part in q.split('&') {
        if part.is_empty() {
            continue;
        }
        let (k, v) = match part.split_once('=') {
            Some((k, v)) => (k, v),
            None => (part, ""),
        };
        if exclude_keys.contains(&k) || k.starts_with("_sm_") {
            continue;
        }
        pairs.push((k, v));
    }
    if pairs.is_empty() {
        return path.to_string();
    }
    pairs.sort();
    let mut out = String::with_capacity(path.len() + q.len() + 1);
    out.push_str(path);
    out.push('?');
    for (i, (k, v)) in pairs.iter().enumerate() {
        if i > 0 {
            out.push('&');
        }
        out.push_str(k);
        out.push('=');
        out.push_str(v);
    }
    out
}

/// Upper bound on a request body we will buffer + digest in the auth
/// middleware for A2 body integrity. Only bodies that opt into the digest
/// (via `x-body-sha256`) or hit a sensitive route are buffered here; the
/// largest legitimate one is a base64 image upload (~12 MB payload → ~16 MB
/// JSON), so 32 MB leaves generous headroom while capping abuse.
const MAX_SIGNED_BODY: usize = 32 * 1024 * 1024;

/// `Content-Length` header as a `usize`, if present and parseable.
fn content_length(headers: &axum::http::HeaderMap) -> Option<usize> {
    headers
        .get(axum::http::header::CONTENT_LENGTH)?
        .to_str()
        .ok()?
        .parse()
        .ok()
}

/// Is `timestamp` within the ±60 s signing window? Mirrors the first check in
/// [`ServerAuth::verify_signature`] so the middleware can reject a stale (or
/// far-future) request *before* buffering its body.
fn timestamp_fresh(timestamp: &str) -> bool {
    match timestamp.parse::<i64>() {
        Ok(ts) => (chrono::Utc::now().timestamp() - ts).abs() <= 60,
        Err(_) => false,
    }
}

/// Lowercase-hex SHA-256 of `bytes`.
fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::Digest;
    let mut h = Sha256::new();
    h.update(bytes);
    hex::encode(h.finalize())
}

/// A2/A4 — routes that inject attacker-controllable text into a
/// skip-permissions agent. These MUST carry a body digest (`x-body-sha256`,
/// folded into the signature) and, when the allowlist is configured, an
/// allowed `x-grove-sender`.
fn is_sensitive_route(method: &str, path: &str) -> bool {
    method == "POST" && (path == "/api/v1/tray/send-prompt" || path.ends_with("/tasks/dispatch"))
}

/// Axum middleware — checks HMAC signature (headers or query params).
///
/// Uses `OriginalUri` so that the path seen here is the full request path
/// (e.g. `/api/v1/projects`) even when the middleware runs inside a `.nest()`.
pub async fn auth_middleware(
    axum::extract::State(auth): axum::extract::State<Arc<ServerAuth>>,
    original_uri: axum::extract::OriginalUri,
    request: Request<Body>,
    next: Next,
) -> Response {
    // No-auth mode → pass through
    if auth.secret_key.is_none() {
        return next.run(request).await;
    }

    let method = request.method().as_str().to_uppercase();
    // Use the original (un-stripped) URI so the path matches what the client signed.
    let path = original_uri.path().to_string();
    let query = original_uri.query().map(|q| q.to_string());
    let sensitive = is_sensitive_route(&method, &path);

    // Header creds + the two hardening headers.
    let from_headers = (|| {
        let ts = request.headers().get("x-timestamp")?.to_str().ok()?;
        let nonce = request.headers().get("x-nonce")?.to_str().ok()?;
        let sig = request.headers().get("x-signature")?.to_str().ok()?;
        Some((ts.to_string(), nonce.to_string(), sig.to_string()))
    })();
    let body_sha_header = request
        .headers()
        .get("x-body-sha256")
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string());
    let sender = request
        .headers()
        .get("x-grove-sender")
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string());

    // A2 gate: a sensitive route with no body digest is a downgrade attempt —
    // refuse before doing anything else. (The digest is folded into the
    // signature below, so an absent digest can never be a valid v2 request.)
    if sensitive && body_sha_header.is_none() {
        auth.audit(&method, &path, sender.as_deref(), "reject:no-body-digest");
        return (StatusCode::UNAUTHORIZED, "body integrity required").into_response();
    }

    // A2/A4 hardening: a sensitive route may ONLY be satisfied by the header-
    // carried v2 (body-signed) branch below. The query-string fallback verifies
    // a body-less legacy message and forwards the body unverified — so without
    // this guard a sensitive POST that omits the HMAC headers but supplies
    // ts/nonce/sig in the query (plus a bogus x-body-sha256 to clear the gate
    // above) would slip past body-binding and the sender allowlist entirely.
    if sensitive && from_headers.is_none() {
        auth.audit(&method, &path, sender.as_deref(), "reject:no-header-creds");
        return (StatusCode::UNAUTHORIZED, "body integrity required").into_response();
    }

    if let Some((ts, nonce, sig)) = from_headers {
        let canonical = canonical_path(&path, query.as_deref(), &[]);

        // v2 (body-signed): buffer the body, digest it ourselves, fold the
        // recomputed digest into the verification, then rebuild the request.
        if let Some(claimed) = body_sha_header {
            // Cheap pre-buffer rejections so a bogus request can't force us to
            // read up to MAX_SIGNED_BODY before any auth work happens:
            //  - a declared Content-Length past the cap is refused outright;
            //  - a timestamp outside the signing window is refused before the
            //    body is read (verify_signature re-checks it afterward too).
            if content_length(request.headers()).is_some_and(|len| len > MAX_SIGNED_BODY) {
                if sensitive {
                    auth.audit(&method, &path, sender.as_deref(), "reject:body-too-large");
                }
                return (StatusCode::PAYLOAD_TOO_LARGE, "body too large").into_response();
            }
            if !timestamp_fresh(&ts) {
                if sensitive {
                    auth.audit(&method, &path, sender.as_deref(), "reject:stale-timestamp");
                }
                return (StatusCode::UNAUTHORIZED, "Invalid signature").into_response();
            }
            let (parts, body) = request.into_parts();
            let bytes = match axum::body::to_bytes(body, MAX_SIGNED_BODY).await {
                Ok(b) => b,
                Err(_) => {
                    if sensitive {
                        auth.audit(&method, &path, sender.as_deref(), "reject:body-too-large");
                    }
                    return (StatusCode::PAYLOAD_TOO_LARGE, "body too large").into_response();
                }
            };
            let actual = sha256_hex(&bytes);
            // The client committed to `claimed`; we bind `actual`. If they
            // differ the signature check below fails anyway, but rejecting here
            // gives a crisp error and skips a doomed HMAC computation.
            if actual != claimed {
                if sensitive {
                    auth.audit(&method, &path, sender.as_deref(), "reject:body-mismatch");
                }
                return (StatusCode::UNAUTHORIZED, "Invalid body digest").into_response();
            }
            if !auth.verify_signature(&ts, &nonce, &method, &canonical, &sig, Some(&actual)) {
                if sensitive {
                    auth.audit(&method, &path, sender.as_deref(), "reject:signature");
                }
                return (StatusCode::UNAUTHORIZED, "Invalid signature").into_response();
            }
            // Authenticated. A4: authorize the sender on sensitive routes.
            if sensitive && !auth.sender_allowed(sender.as_deref()) {
                auth.audit(&method, &path, sender.as_deref(), "reject:sender");
                return (StatusCode::FORBIDDEN, "sender not authorized").into_response();
            }
            if sensitive {
                auth.audit(&method, &path, sender.as_deref(), "accept");
            }
            let request = Request::from_parts(parts, Body::from(bytes));
            return next.run(request).await;
        }

        // Legacy (body-less message) — GETs and non-sensitive writes that
        // haven't adopted the digest. Sensitive routes never reach here (gated
        // above), so no unsigned body can drive a skip-permissions agent.
        if auth.verify_signature(&ts, &nonce, &method, &canonical, &sig, None) {
            return next.run(request).await;
        }
        return (StatusCode::UNAUTHORIZED, "Invalid signature").into_response();
    }

    // Fallback: query params (WebSocket upgrade). The signature itself rides
    // on the URL as `ts/nonce/sig`, so we strip those three keys before
    // canonicalizing — otherwise the signature would have to sign itself.
    // WS upgrades carry no body, so the digest is always absent here.
    if let Some(query) = query.as_deref() {
        if let (Some(ts), Some(nonce), Some(sig)) = (
            query_param(query, "ts"),
            query_param(query, "nonce"),
            query_param(query, "sig"),
        ) {
            let canonical = canonical_path(&path, Some(query), &["ts", "nonce", "sig"]);
            if auth.verify_signature(ts, nonce, &method, &canonical, sig, None) {
                return next.run(request).await;
            }
            return (StatusCode::UNAUTHORIZED, "Invalid signature").into_response();
        }
    }

    (StatusCode::UNAUTHORIZED, "Unauthorized").into_response()
}

#[derive(Serialize)]
pub struct AuthInfoResponse {
    pub required: bool,
    pub mode: AuthMode,
    /// See [`ServerAuth::remote`]. The frontend treats `remote || required`
    /// as "don't trust server-side native OS dialogs" — this field is what
    /// actually makes that true for a no-auth `grove web --remote` instance.
    pub remote: bool,
}

/// `GET /api/v1/auth/info` — tells the SPA whether auth is required and which mode.
pub async fn auth_info(
    axum::extract::State(auth): axum::extract::State<Arc<ServerAuth>>,
) -> Json<AuthInfoResponse> {
    Json(AuthInfoResponse {
        required: auth.secret_key.is_some(),
        mode: auth.mode,
        remote: auth.remote,
    })
}

#[derive(Deserialize)]
pub struct VerifyRequest {
    pub proof: String,
}

#[derive(Serialize)]
pub struct VerifyResponse {
    pub valid: bool,
}

/// `POST /api/v1/auth/verify` — client sends `HMAC(SK, "grove-verify")` as proof.
pub async fn auth_verify(
    axum::extract::State(auth): axum::extract::State<Arc<ServerAuth>>,
    Json(req): Json<VerifyRequest>,
) -> Result<Json<VerifyResponse>, StatusCode> {
    match &auth.secret_key {
        None => Ok(Json(VerifyResponse { valid: true })),
        Some(sk) => {
            let mut mac =
                HmacSha256::new_from_slice(sk.as_bytes()).expect("HMAC accepts any key length");
            mac.update(b"grove-verify");
            let expected = hex::encode(mac.finalize().into_bytes());

            if req.proof == expected {
                Ok(Json(VerifyResponse { valid: true }))
            } else {
                Err(StatusCode::UNAUTHORIZED)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{canonical_path, is_sensitive_route, sha256_hex, ServerAuth};
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    /// Client-side signer mirror (matches grove_client.py / file_bug.py / client.ts).
    fn client_sig(
        key: &str,
        ts: &str,
        nonce: &str,
        method: &str,
        path: &str,
        body_sha: Option<&str>,
    ) -> String {
        let msg = match body_sha {
            Some(d) => format!("{}|{}|{}|{}|{}", ts, nonce, method, path, d),
            None => format!("{}|{}|{}|{}", ts, nonce, method, path),
        };
        let mut mac = Hmac::<Sha256>::new_from_slice(key.as_bytes()).unwrap();
        mac.update(msg.as_bytes());
        hex::encode(mac.finalize().into_bytes())
    }

    #[test]
    fn no_query() {
        assert_eq!(canonical_path("/a/b", None, &[]), "/a/b");
        assert_eq!(canonical_path("/a/b", Some(""), &[]), "/a/b");
    }

    #[test]
    fn single_param() {
        assert_eq!(
            canonical_path("/api/v1/x", Some("offset=0"), &[]),
            "/api/v1/x?offset=0"
        );
    }

    #[test]
    fn sorts_by_key() {
        let a = canonical_path("/x", Some("b=2&a=1&c=3"), &[]);
        let b = canonical_path("/x", Some("a=1&b=2&c=3"), &[]);
        let c = canonical_path("/x", Some("c=3&a=1&b=2"), &[]);
        assert_eq!(a, "/x?a=1&b=2&c=3");
        assert_eq!(a, b);
        assert_eq!(a, c);
    }

    #[test]
    fn excludes_keys() {
        let canonical = canonical_path(
            "/ws",
            Some("ts=1&offset=0&nonce=abc&sig=def"),
            &["ts", "nonce", "sig"],
        );
        assert_eq!(canonical, "/ws?offset=0");
    }

    #[test]
    fn exclude_all_leaves_path_only() {
        let canonical = canonical_path(
            "/ws",
            Some("ts=1&nonce=abc&sig=def"),
            &["ts", "nonce", "sig"],
        );
        assert_eq!(canonical, "/ws");
    }

    #[test]
    fn value_without_equals() {
        // `?flag` (no =) → key "flag", value ""
        assert_eq!(canonical_path("/x", Some("flag"), &[]), "/x?flag=");
    }

    #[test]
    fn ignores_waf_security_params() {
        assert_eq!(
            canonical_path("/x", Some("b=2&_sm_nck=1&a=1&_sm_byp=123"), &[]),
            "/x?a=1&b=2"
        );
    }

    #[test]
    fn sensitive_route_detection() {
        assert!(is_sensitive_route("POST", "/api/v1/tray/send-prompt"));
        assert!(is_sensitive_route(
            "POST",
            "/api/v1/projects/abc/tasks/dispatch"
        ));
        // Wrong method, or a read/other route, is not sensitive.
        assert!(!is_sensitive_route("GET", "/api/v1/tray/send-prompt"));
        assert!(!is_sensitive_route(
            "POST",
            "/api/v1/tray/resolve-permission"
        ));
        assert!(!is_sensitive_route("POST", "/api/v1/projects/abc/tasks"));
    }

    #[test]
    fn legacy_signature_still_verifies() {
        let key = "test-key-123";
        let auth = ServerAuth::hmac(key.to_string(), false);
        let ts = chrono::Utc::now().timestamp().to_string();
        let sig = client_sig(key, &ts, "n1", "GET", "/api/v1/projects", None);
        assert!(auth.verify_signature(&ts, "n1", "GET", "/api/v1/projects", &sig, None));
    }

    #[test]
    fn body_signed_signature_verifies_and_binds_body() {
        let key = "test-key-123";
        let auth = ServerAuth::hmac(key.to_string(), false);
        let ts = chrono::Utc::now().timestamp().to_string();
        let body = br#"{"text":"hello"}"#;
        let digest = sha256_hex(body);
        let sig = client_sig(
            key,
            &ts,
            "n2",
            "POST",
            "/api/v1/tray/send-prompt",
            Some(&digest),
        );
        // Correct digest verifies.
        assert!(auth.verify_signature(
            &ts,
            "n2",
            "POST",
            "/api/v1/tray/send-prompt",
            &sig,
            Some(&digest)
        ));
        // Body-binding proof: change ONLY the digest — same ts, same nonce, same
        // signature — on a FRESH auth so the nonce map is empty and can't be the
        // reason it fails. A tampered body yields a different digest, so the
        // (still valid, still unused) signature must no longer verify.
        let auth2 = ServerAuth::hmac(key.to_string(), false);
        let tampered = sha256_hex(br#"{"text":"HELLO EVIL"}"#);
        assert!(!auth2.verify_signature(
            &ts,
            "n2",
            "POST",
            "/api/v1/tray/send-prompt",
            &sig,
            Some(&tampered)
        ));
    }

    #[test]
    fn scheme_versions_do_not_cross_verify() {
        // A legacy-signed signature must not validate under the v2 (body) msg
        // and vice-versa, so a MITM can't strip the digest field.
        let key = "k";
        let auth = ServerAuth::hmac(key.to_string(), false);
        let ts = chrono::Utc::now().timestamp().to_string();
        let digest = sha256_hex(b"{}");
        let legacy_sig = client_sig(key, &ts, "a", "POST", "/p", None);
        assert!(!auth.verify_signature(&ts, "a", "POST", "/p", &legacy_sig, Some(&digest)));
        let v2_sig = client_sig(key, &ts, "b", "POST", "/p", Some(&digest));
        assert!(!auth.verify_signature(&ts, "b", "POST", "/p", &v2_sig, None));
    }

    #[test]
    fn sender_allowlist_semantics() {
        // Empty allowlist ⇒ enforcement off, everything allowed.
        let open = ServerAuth::hmac("k".to_string(), false);
        assert!(open.sender_allowlist.is_empty());
        assert!(open.sender_allowed(None));
        assert!(open.sender_allowed(Some("anyone")));

        // Non-empty ⇒ fail closed.
        let mut gated = ServerAuth::hmac("k".to_string(), false);
        gated.sender_allowlist = vec!["nanobot".into(), "grove-web".into()];
        assert!(gated.sender_allowed(Some("nanobot")));
        assert!(gated.sender_allowed(Some("grove-web")));
        assert!(!gated.sender_allowed(Some("intruder")));
        assert!(!gated.sender_allowed(None));
    }
}
